name: Release

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:        
      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        id: build-addon  # Add an id so we can refer to the output later
        with:
          name: paint-system
          exclude-files: ".git;.github;README.md"
      
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: paint-system # Use the same name as in the build step, or the name of your choosing
          path: ${{ steps.build-addon.outputs.zip-location }} # get the zip location from the previous step
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: paint-system  # Use the same name that was used for uploading the artifact
      - name: Release addon
        uses: blenderkit/blender-addon-release@main
        with:
          artifact_name: paint-system # Use the artifact name.
          release_name: PaintSystem
          version: ${{github.event.inputs.version}}
