name: Release

on:
    pull_request:
        branches: ['**']
    workflow_dispatch:
        inputs:
            version:
                description: 'version'
                required: false # Make this optional
                default: ''

permissions:
    contents: write

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Extract version from __init__.py
              id: extract_version
              run: |
                  VERSION=$(python <<EOF
                  import re

                  with open("__init__.py", "r", encoding="utf-8") as f:
                      content = f.read()

                  # Try matching either `"version": (x, y, z)` or `version = (x, y, z)`
                  pattern = re.compile(r'version"\s*:\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)|version\s*=\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)')
                  match = pattern.search(content)

                  if not match:
                      # If no match, print nothing; shell script will handle error
                      print("")
                  else:
                      # The pattern has up to 6 capturing groups, so we combine the ones that matched
                      # Groups 1-3 (for "version": (x, y, z)) or 4-6 (for version = (x, y, z))
                      groups = [g for g in match.groups() if g]
                      print(".".join(groups))
                  EOF
                  )
                      if [ -z "$VERSION" ]; then
                      echo "Error: Version could not be extracted from __init__.py"
                      exit 1
                      fi

                      echo "VERSION=$VERSION"
                      echo "version=$VERSION" >> $GITHUB_ENV

            - name: Validate version
              id: validate_version
              run: |
                  if [[ -z "${{ env.version }}" ]]; then
                    echo "Error: Extracted version is invalid."
                    exit 1
                  else
                    echo "Extracted version: ${{ env.version }}"
                  fi

            - name: Build addon
              uses: blenderkit/blender-addon-build@main
              with:
                  name: paint-system
                  exclude-files: '.git;.github;README.md'

    Release:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Release addon
              uses: blenderkit/blender-addon-release@main
              with:
                  artifact_name: paint-system
                  release_name: Paint System
                  version: ${{ env.version }}
